// Package s3opgen generates the s3op catalog and its constants from
// operations.json. It decodes the JSON into its own types rather than
// s3op's, so a stale or broken generated file never keeps it from building.
package s3opgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"slices"
	"strings"
	"text/template"
)

// Paths, relative to the s3op package directory.
const (
	SourceFile = "operations.json"
	OutputFile = "s3op_gen.go"
)

type catalog struct {
	Operations []operation `json:"operations"`
}

type operation struct {
	Name           string          `json:"name"`
	Scope          string          `json:"scope"`
	Support        string          `json:"support"`
	Authorizations []authorization `json:"authorizations"`
	Note           string          `json:"note"`
}

type authorization struct {
	Action string `json:"action"`
	On     string `json:"on"`
	Header string `json:"header"`
}

var (
	scopes    = map[string]string{"service": "ScopeService", "bucket": "ScopeBucket", "object": "ScopeObject"}
	supports  = map[string]string{"supported": "Supported", "refused": "Refused"}
	resources = map[string]string{"target": "OnTarget", "copy-source": "OnCopySource", "each-key": "OnEachKey"}

	namePattern   = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
	actionPattern = regexp.MustCompile(`^s3:[A-Z][A-Za-z0-9]*$`)
)

type constant struct{ Name, Value string }

type data struct {
	Operations []operation
	Actions    []constant
	Scopes     map[string]string
	Supports   map[string]string
	Resources  map[string]string
}

// File returns the generated Go source for the catalog in src.
func File(src []byte) ([]byte, error) {
	dec := json.NewDecoder(bytes.NewReader(src))
	dec.DisallowUnknownFields()
	var c catalog
	if err := dec.Decode(&c); err != nil {
		return nil, fmt.Errorf("%s: %w", SourceFile, err)
	}
	actions, err := validate(c)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", SourceFile, err)
	}
	var buf bytes.Buffer
	d := data{c.Operations, actions, scopes, supports, resources}
	if err := tmpl.Execute(&buf, d); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}

// Generate reads the source in dir and returns the generated file's path
// and content.
func Generate(dir string) (string, []byte, error) {
	src, err := os.ReadFile(dir + "/" + SourceFile)
	if err != nil {
		return "", nil, err
	}
	out, err := File(src)
	return dir + "/" + OutputFile, out, err
}

func validate(c catalog) ([]constant, error) {
	seen := map[string]bool{}
	actionSet := map[string]bool{}
	for _, op := range c.Operations {
		if !namePattern.MatchString(op.Name) {
			return nil, fmt.Errorf("operation name %q: not an S3 operation name", op.Name)
		}
		if seen[op.Name] {
			return nil, fmt.Errorf("operation %s: duplicate", op.Name)
		}
		seen[op.Name] = true
		if scopes[op.Scope] == "" {
			return nil, fmt.Errorf("operation %s: unknown scope %q", op.Name, op.Scope)
		}
		if supports[op.Support] == "" {
			return nil, fmt.Errorf("operation %s: unknown support %q", op.Name, op.Support)
		}
		if op.Support == "refused" && len(op.Authorizations) > 0 {
			return nil, fmt.Errorf("operation %s: a refused operation authorizes nothing", op.Name)
		}
		for _, a := range op.Authorizations {
			if !actionPattern.MatchString(a.Action) {
				return nil, fmt.Errorf("operation %s: action %q: not an s3: action", op.Name, a.Action)
			}
			if resources[a.On] == "" {
				return nil, fmt.Errorf("operation %s: action %s: unknown resource %q", op.Name, a.Action, a.On)
			}
			if a.Header != strings.ToLower(a.Header) {
				return nil, fmt.Errorf("operation %s: header %q must be lower case", op.Name, a.Header)
			}
			actionSet[a.Action] = true
		}
	}
	var actions []constant
	for a := range actionSet {
		actions = append(actions, constant{"Action" + strings.TrimPrefix(a, "s3:"), a})
	}
	slices.SortFunc(actions, func(a, b constant) int { return strings.Compare(a.Value, b.Value) })
	return actions, nil
}

var tmpl = template.Must(template.New("s3op").Parse(`// Code generated by s3op/internal/s3opgen from operations.json; DO NOT EDIT.

package s3op

// Operation names, the values of Op.Operation.
const (
{{- range .Operations}}
	Op{{.Name}} = "{{.Name}}"
{{- end}}
)

// Actions some operation authorizes.
const (
{{- range .Actions}}
	{{.Name}} = "{{.Value}}"
{{- end}}
)

var operations = []Operation{
{{- range .Operations}}
	{
		Name:    Op{{.Name}},
		Scope:   {{index $.Scopes .Scope}},
		Support: {{index $.Supports .Support}},
{{- if .Authorizations}}
		Authorizations: []Authorization{
{{- range .Authorizations}}
			{Action: Action{{slice .Action 3}}, On: {{index $.Resources .On}}{{if .Header}}, Header: {{printf "%q" .Header}}{{end}}},
{{- end}}
		},
{{- end}}
{{- if .Note}}
		Note: {{printf "%q" .Note}},
{{- end}}
	},
{{- end}}
}

var actions = []string{
{{- range .Actions}}
	{{.Name}},
{{- end}}
}
`))
