version: 2
before:
  hooks:
    - go mod download
builds:
  - id: s3rp
    env:
      - CGO_ENABLED=0
    main: ./cmd/s3rp/
    binary: s3rp
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
  use_existing_draft: true
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
