// Code generated by s3gw/internal/checksumgen; DO NOT EDIT.

package s3gw

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/fujiwara/s3rp/checksum"
	"github.com/fujiwara/s3rp/s3xml"
)

// addChecksum records a present, non-empty value; v stays nil until one is.
func addChecksum(v *checksum.Values, name string, p *string) {
	if p == nil || *p == "" {
		return
	}
	if *v == nil {
		*v = checksum.Values{}
	}
	(*v)[name] = *p
}

// checksumPtr is the SDK's spelling of a value: nil when absent.
func checksumPtr(v checksum.Values, name string) *string {
	if s := v[name]; s != "" {
		return &s
	}
	return nil
}

func checksumsFromGetObjectOutput(x *s3.GetObjectOutput) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromHeadObjectOutput(x *s3.HeadObjectOutput) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromPutObjectOutput(x *s3.PutObjectOutput) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromUploadPartOutput(x *s3.UploadPartOutput) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromCompleteMultipartUploadOutput(x *s3.CompleteMultipartUploadOutput) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromCopyObjectResult(x *types.CopyObjectResult) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromCopyPartResult(x *types.CopyPartResult) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromPart(x *types.Part) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromChecksum(x *types.Checksum) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func checksumsFromObjectPart(x *types.ObjectPart) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", x.ChecksumCRC32)
	addChecksum(&v, "CRC32C", x.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", x.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", x.ChecksumSHA1)
	addChecksum(&v, "SHA256", x.ChecksumSHA256)
	addChecksum(&v, "SHA512", x.ChecksumSHA512)
	addChecksum(&v, "MD5", x.ChecksumMD5)
	addChecksum(&v, "XXHASH64", x.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", x.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", x.ChecksumXXHASH128)
	return v
}

func setChecksumsPutObjectInput(x *s3.PutObjectInput, v checksum.Values) {
	x.ChecksumCRC32 = checksumPtr(v, "CRC32")
	x.ChecksumCRC32C = checksumPtr(v, "CRC32C")
	x.ChecksumCRC64NVME = checksumPtr(v, "CRC64NVME")
	x.ChecksumSHA1 = checksumPtr(v, "SHA1")
	x.ChecksumSHA256 = checksumPtr(v, "SHA256")
	x.ChecksumSHA512 = checksumPtr(v, "SHA512")
	x.ChecksumMD5 = checksumPtr(v, "MD5")
	x.ChecksumXXHASH64 = checksumPtr(v, "XXHASH64")
	x.ChecksumXXHASH3 = checksumPtr(v, "XXHASH3")
	x.ChecksumXXHASH128 = checksumPtr(v, "XXHASH128")
}

func setChecksumsUploadPartInput(x *s3.UploadPartInput, v checksum.Values) {
	x.ChecksumCRC32 = checksumPtr(v, "CRC32")
	x.ChecksumCRC32C = checksumPtr(v, "CRC32C")
	x.ChecksumCRC64NVME = checksumPtr(v, "CRC64NVME")
	x.ChecksumSHA1 = checksumPtr(v, "SHA1")
	x.ChecksumSHA256 = checksumPtr(v, "SHA256")
	x.ChecksumSHA512 = checksumPtr(v, "SHA512")
	x.ChecksumMD5 = checksumPtr(v, "MD5")
	x.ChecksumXXHASH64 = checksumPtr(v, "XXHASH64")
	x.ChecksumXXHASH3 = checksumPtr(v, "XXHASH3")
	x.ChecksumXXHASH128 = checksumPtr(v, "XXHASH128")
}

func setChecksumsCompleteMultipartUploadInput(x *s3.CompleteMultipartUploadInput, v checksum.Values) {
	x.ChecksumCRC32 = checksumPtr(v, "CRC32")
	x.ChecksumCRC32C = checksumPtr(v, "CRC32C")
	x.ChecksumCRC64NVME = checksumPtr(v, "CRC64NVME")
	x.ChecksumSHA1 = checksumPtr(v, "SHA1")
	x.ChecksumSHA256 = checksumPtr(v, "SHA256")
	x.ChecksumSHA512 = checksumPtr(v, "SHA512")
	x.ChecksumMD5 = checksumPtr(v, "MD5")
	x.ChecksumXXHASH64 = checksumPtr(v, "XXHASH64")
	x.ChecksumXXHASH3 = checksumPtr(v, "XXHASH3")
	x.ChecksumXXHASH128 = checksumPtr(v, "XXHASH128")
}

func setChecksumsCompletedPart(x *types.CompletedPart, v checksum.Values) {
	x.ChecksumCRC32 = checksumPtr(v, "CRC32")
	x.ChecksumCRC32C = checksumPtr(v, "CRC32C")
	x.ChecksumCRC64NVME = checksumPtr(v, "CRC64NVME")
	x.ChecksumSHA1 = checksumPtr(v, "SHA1")
	x.ChecksumSHA256 = checksumPtr(v, "SHA256")
	x.ChecksumSHA512 = checksumPtr(v, "SHA512")
	x.ChecksumMD5 = checksumPtr(v, "MD5")
	x.ChecksumXXHASH64 = checksumPtr(v, "XXHASH64")
	x.ChecksumXXHASH3 = checksumPtr(v, "XXHASH3")
	x.ChecksumXXHASH128 = checksumPtr(v, "XXHASH128")
}

func xmlChecksums(v checksum.Values) s3xml.Checksums {
	return s3xml.Checksums{
		ChecksumCRC32:     v["CRC32"],
		ChecksumCRC32C:    v["CRC32C"],
		ChecksumCRC64NVME: v["CRC64NVME"],
		ChecksumSHA1:      v["SHA1"],
		ChecksumSHA256:    v["SHA256"],
		ChecksumSHA512:    v["SHA512"],
		ChecksumMD5:       v["MD5"],
		ChecksumXXHASH64:  v["XXHASH64"],
		ChecksumXXHASH3:   v["XXHASH3"],
		ChecksumXXHASH128: v["XXHASH128"],
	}
}

func checksumsFromXML(c s3xml.Checksums) checksum.Values {
	var v checksum.Values
	addChecksum(&v, "CRC32", &c.ChecksumCRC32)
	addChecksum(&v, "CRC32C", &c.ChecksumCRC32C)
	addChecksum(&v, "CRC64NVME", &c.ChecksumCRC64NVME)
	addChecksum(&v, "SHA1", &c.ChecksumSHA1)
	addChecksum(&v, "SHA256", &c.ChecksumSHA256)
	addChecksum(&v, "SHA512", &c.ChecksumSHA512)
	addChecksum(&v, "MD5", &c.ChecksumMD5)
	addChecksum(&v, "XXHASH64", &c.ChecksumXXHASH64)
	addChecksum(&v, "XXHASH3", &c.ChecksumXXHASH3)
	addChecksum(&v, "XXHASH128", &c.ChecksumXXHASH128)
	return v
}
