// Code generated by weaver from model/. DO NOT EDIT.

package semconv

// Attribute keys used by the s3gw metrics.
const (
	// AttrAWSS3Bucket is aws.s3.bucket: The front bucket name (`Op.Bucket`).
	AttrAWSS3Bucket = "aws.s3.bucket"
	// AttrErrorType is error.type: The S3 error code the client was given, `_OTHER` for a failure without one.
	AttrErrorType = "error.type"
	// AttrHTTPRequestMethod is http.request.method: HTTP request method.
	AttrHTTPRequestMethod = "http.request.method"
	// AttrHTTPResponseStatusCode is http.response.status_code: [HTTP response status code](https://tools.ietf.org/html/rfc7231#section-6).
	AttrHTTPResponseStatusCode = "http.response.status_code"
	// AttrNetworkIODirection is network.io.direction: `receive` for the request body, `transmit` for the response body.
	AttrNetworkIODirection = "network.io.direction"
	// AttrS3GWCacheName is s3gw.cache.name: Which cache the measurement is about.
	AttrS3GWCacheName = "s3gw.cache.name"
	// AttrS3GWCacheResult is s3gw.cache.result: Whether a cache lookup found its entry.
	AttrS3GWCacheResult = "s3gw.cache.result"
	// AttrS3GWOperation is s3gw.operation: The S3 API operation the request resolved to (`Op.Operation`).
	AttrS3GWOperation = "s3gw.operation"
	// AttrS3GWTenant is s3gw.tenant: The tenant whose signature the request carried (`RequestInfo.Tenant`).
	AttrS3GWTenant = "s3gw.tenant"
)

// Values of network.io.direction.
const (
	NetworkIODirectionTransmit = "transmit"
	NetworkIODirectionReceive  = "receive"
)

// Values of s3gw.cache.name.
const (
	S3GWCacheNameSigner = "signer"
	S3GWCacheNameClient = "client"
)

// Values of s3gw.cache.result.
const (
	S3GWCacheResultHit  = "hit"
	S3GWCacheResultMiss = "miss"
)

// s3gw.cache.capacity (updowncounter): Capacity of the gateway's caches (`CacheStats.Capacity`).
const (
	MetricS3GWCacheCapacity            = "s3gw.cache.capacity"
	MetricS3GWCacheCapacityUnit        = "{entry}"
	MetricS3GWCacheCapacityDescription = "Capacity of the gateway's caches (`CacheStats.Capacity`)."
)

// s3gw.cache.entries (updowncounter): Entries currently held in the gateway's caches (`CacheStats.Len`).
const (
	MetricS3GWCacheEntries            = "s3gw.cache.entries"
	MetricS3GWCacheEntriesUnit        = "{entry}"
	MetricS3GWCacheEntriesDescription = "Entries currently held in the gateway's caches (`CacheStats.Len`)."
)

// s3gw.cache.evictions (counter): Entries evicted from the gateway's caches (`CacheStats.Evictions`).
const (
	MetricS3GWCacheEvictions            = "s3gw.cache.evictions"
	MetricS3GWCacheEvictionsUnit        = "{entry}"
	MetricS3GWCacheEvictionsDescription = "Entries evicted from the gateway's caches (`CacheStats.Evictions`)."
)

// s3gw.cache.lookups (counter): Lookups in the gateway's caches, by result (`CacheStats.Hits` / `Misses`).
const (
	MetricS3GWCacheLookups            = "s3gw.cache.lookups"
	MetricS3GWCacheLookupsUnit        = "{lookup}"
	MetricS3GWCacheLookupsDescription = "Lookups in the gateway's caches, by result (`CacheStats.Hits` / `Misses`)."
)

// s3gw.io (counter): Request and response body bytes as seen on the wire (`RequestInfo.BytesIn` / `BytesOut`).
const (
	MetricS3GWIO            = "s3gw.io"
	MetricS3GWIOUnit        = "By"
	MetricS3GWIODescription = "Request and response body bytes as seen on the wire (`RequestInfo.BytesIn` / `BytesOut`)."
)

// s3gw.request.duration (histogram): Duration of requests served by the gateway (`RequestInfo.Duration`).
const (
	MetricS3GWRequestDuration            = "s3gw.request.duration"
	MetricS3GWRequestDurationUnit        = "s"
	MetricS3GWRequestDurationDescription = "Duration of requests served by the gateway (`RequestInfo.Duration`)."
)
