// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readdb

type AccessKey struct {
	AccessKeyID     string
	UserID          int64
	SecretAccessKey string
}

type Bucket struct {
	ID       int64
	TenantID int64
	Name     string
	Backend  string
	Policy   string
	Cors     string
}

type Tenant struct {
	ID   int64
	Name string
}

type User struct {
	ID       int64
	TenantID int64
	Name     string
}
