// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package readdb

import (
	"context"
)

const getBucket = `-- name: GetBucket :one
SELECT b.name, b.backend, b.policy, b.cors, t.name AS tenant_name
FROM buckets b
JOIN tenants t ON t.id = b.tenant_id
WHERE t.name = ? AND b.name = ?
`

type GetBucketParams struct {
	Name   string
	Name_2 string
}

type GetBucketRow struct {
	Name       string
	Backend    string
	Policy     string
	Cors       string
	TenantName string
}

func (q *Queries) GetBucket(ctx context.Context, arg GetBucketParams) (GetBucketRow, error) {
	row := q.db.QueryRowContext(ctx, getBucket, arg.Name, arg.Name_2)
	var i GetBucketRow
	err := row.Scan(
		&i.Name,
		&i.Backend,
		&i.Policy,
		&i.Cors,
		&i.TenantName,
	)
	return i, err
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT b.name, b.backend, b.policy, b.cors, t.name AS tenant_name
FROM buckets b
JOIN tenants t ON t.id = b.tenant_id
WHERE b.name = ?
`

type GetBucketByNameRow struct {
	Name       string
	Backend    string
	Policy     string
	Cors       string
	TenantName string
}

func (q *Queries) GetBucketByName(ctx context.Context, name string) (GetBucketByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketByName, name)
	var i GetBucketByNameRow
	err := row.Scan(
		&i.Name,
		&i.Backend,
		&i.Policy,
		&i.Cors,
		&i.TenantName,
	)
	return i, err
}

const getKey = `-- name: GetKey :one

SELECT ak.access_key_id, ak.secret_access_key, u.name AS user_name, t.name AS tenant_name
FROM access_keys ak
JOIN users u ON u.id = ak.user_id
JOIN tenants t ON t.id = u.tenant_id
WHERE ak.access_key_id = ?
`

type GetKeyRow struct {
	AccessKeyID     string
	SecretAccessKey string
	UserName        string
	TenantName      string
}

// Read-only queries used by the proxy (store/rdb).
// Do not add INSERT/UPDATE/DELETE here; writes belong to write.sql,
// which is generated into a package the proxy never imports.
func (q *Queries) GetKey(ctx context.Context, accessKeyID string) (GetKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getKey, accessKeyID)
	var i GetKeyRow
	err := row.Scan(
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.UserName,
		&i.TenantName,
	)
	return i, err
}

const listBucketNames = `-- name: ListBucketNames :many
SELECT b.name
FROM buckets b
JOIN tenants t ON t.id = b.tenant_id
WHERE t.name = ?
`

func (q *Queries) ListBucketNames(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBucketNames, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantExists = `-- name: TenantExists :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE name = ?)
`

func (q *Queries) TenantExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tenantExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
