// Package checksumgen generates the conversions between checksum.Values and
// the per-algorithm fields of the SDK types and the s3xml bodies. The SDK
// spells every algorithm as its own field (ChecksumCRC32, ChecksumSHA512, ...)
// on each type, so without generation each algorithm is a hand-written line
// at every site, and an algorithm added to the table would be silently
// dropped wherever one was missed.
//
// The code is generated for every algorithm in checksum.Algorithms whatever
// its Support: the gates read Support, the conversions do not, so changing
// an algorithm's Support needs no regeneration — adding one to the table
// does.
package checksumgen

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"

	"github.com/fujiwara/s3rp/checksum"
)

// sdkType is an SDK type carrying one Checksum<Name> field per algorithm.
type sdkType struct {
	Name string // the Go type, qualified: "s3.GetObjectOutput"
	Func string // the suffix of the generated function names
}

// readTypes are the backend's answers the gateway reports to the client.
var readTypes = []sdkType{
	{"s3.GetObjectOutput", "GetObjectOutput"},
	{"s3.HeadObjectOutput", "HeadObjectOutput"},
	{"s3.PutObjectOutput", "PutObjectOutput"},
	{"s3.UploadPartOutput", "UploadPartOutput"},
	{"s3.CompleteMultipartUploadOutput", "CompleteMultipartUploadOutput"},
	{"types.CopyObjectResult", "CopyObjectResult"},
	{"types.CopyPartResult", "CopyPartResult"},
	{"types.Part", "Part"},
	{"types.Checksum", "Checksum"},
	{"types.ObjectPart", "ObjectPart"},
}

// writeTypes are the requests the gateway sends the backend.
var writeTypes = []sdkType{
	{"s3.PutObjectInput", "PutObjectInput"},
	{"s3.UploadPartInput", "UploadPartInput"},
	{"s3.CompleteMultipartUploadInput", "CompleteMultipartUploadInput"},
	{"types.CompletedPart", "CompletedPart"},
}

// Output paths, relative to the s3gw package directory.
const (
	GatewayFile = "checksums_gen.go"
	XMLFile     = "../s3xml/checksums_gen.go"
)

const header = "// Code generated by s3gw/internal/checksumgen; DO NOT EDIT.\n\n"

var gatewayTmpl = template.Must(template.New("gw").Parse(header + `package s3gw

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/fujiwara/s3rp/checksum"
	"github.com/fujiwara/s3rp/s3xml"
)

// addChecksum records a present, non-empty value; v stays nil until one is.
func addChecksum(v *checksum.Values, name string, p *string) {
	if p == nil || *p == "" {
		return
	}
	if *v == nil {
		*v = checksum.Values{}
	}
	(*v)[name] = *p
}

// checksumPtr is the SDK's spelling of a value: nil when absent.
func checksumPtr(v checksum.Values, name string) *string {
	if s := v[name]; s != "" {
		return &s
	}
	return nil
}
{{range $t := .Read}}
func checksumsFrom{{$t.Func}}(x *{{$t.Name}}) checksum.Values {
	var v checksum.Values
{{- range $.Algorithms}}
	addChecksum(&v, "{{.Name}}", x.Checksum{{.Name}})
{{- end}}
	return v
}
{{end}}{{range $t := .Write}}
func setChecksums{{$t.Func}}(x *{{$t.Name}}, v checksum.Values) {
{{- range $.Algorithms}}
	x.Checksum{{.Name}} = checksumPtr(v, "{{.Name}}")
{{- end}}
}
{{end}}
func xmlChecksums(v checksum.Values) s3xml.Checksums {
	return s3xml.Checksums{
{{- range .Algorithms}}
		Checksum{{.Name}}: v["{{.Name}}"],
{{- end}}
	}
}

func checksumsFromXML(c s3xml.Checksums) checksum.Values {
	var v checksum.Values
{{- range .Algorithms}}
	addChecksum(&v, "{{.Name}}", &c.Checksum{{.Name}})
{{- end}}
	return v
}
`))

var xmlTmpl = template.Must(template.New("xml").Parse(header + `package s3xml

// Checksums is the per-algorithm checksum elements of a body, embedded so
// they sit directly in the enclosing element as S3 lays them out.
type Checksums struct {
{{- range .Algorithms}}
	Checksum{{.Name}} string ` + "`" + `xml:"Checksum{{.Name}},omitempty"` + "`" + `
{{- end}}
}
`))

// Files returns the generated sources keyed by GatewayFile and XMLFile.
func Files() (map[string][]byte, error) {
	data := struct {
		Algorithms  []checksum.Algorithm
		Read, Write []sdkType
	}{checksum.Algorithms(), readTypes, writeTypes}
	files := map[string][]byte{}
	for path, tmpl := range map[string]*template.Template{GatewayFile: gatewayTmpl, XMLFile: xmlTmpl} {
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		src, err := format.Source(buf.Bytes())
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		files[path] = src
	}
	return files, nil
}
