// Code generated by s3op/internal/s3opgen from operations.json; DO NOT EDIT.

package s3op

// Operation names, the values of Op.Operation.
const (
	OpListBuckets                   = "ListBuckets"
	OpHeadBucket                    = "HeadBucket"
	OpListObjects                   = "ListObjects"
	OpListObjectsV2                 = "ListObjectsV2"
	OpListObjectVersions            = "ListObjectVersions"
	OpListMultipartUploads          = "ListMultipartUploads"
	OpGetBucketLocation             = "GetBucketLocation"
	OpGetBucketAcl                  = "GetBucketAcl"
	OpGetBucketPolicy               = "GetBucketPolicy"
	OpGetBucketPolicyStatus         = "GetBucketPolicyStatus"
	OpGetBucketCors                 = "GetBucketCors"
	OpGetBucketVersioning           = "GetBucketVersioning"
	OpGetBucketEncryption           = "GetBucketEncryption"
	OpGetBucketOwnershipControls    = "GetBucketOwnershipControls"
	OpGetPublicAccessBlock          = "GetPublicAccessBlock"
	OpGetObjectLockConfiguration    = "GetObjectLockConfiguration"
	OpDeleteObjects                 = "DeleteObjects"
	OpPostObject                    = "PostObject"
	OpCreateBucket                  = "CreateBucket"
	OpDeleteBucket                  = "DeleteBucket"
	OpPutBucketAcl                  = "PutBucketAcl"
	OpPutBucketPolicy               = "PutBucketPolicy"
	OpDeleteBucketPolicy            = "DeleteBucketPolicy"
	OpPutBucketCors                 = "PutBucketCors"
	OpDeleteBucketCors              = "DeleteBucketCors"
	OpPutBucketVersioning           = "PutBucketVersioning"
	OpPutObjectLockConfiguration    = "PutObjectLockConfiguration"
	OpPutBucketEncryption           = "PutBucketEncryption"
	OpDeleteBucketEncryption        = "DeleteBucketEncryption"
	OpPutBucketOwnershipControls    = "PutBucketOwnershipControls"
	OpDeleteBucketOwnershipControls = "DeleteBucketOwnershipControls"
	OpPutPublicAccessBlock          = "PutPublicAccessBlock"
	OpDeletePublicAccessBlock       = "DeletePublicAccessBlock"
	OpGetObject                     = "GetObject"
	OpHeadObject                    = "HeadObject"
	OpGetObjectAttributes           = "GetObjectAttributes"
	OpPutObject                     = "PutObject"
	OpCopyObject                    = "CopyObject"
	OpDeleteObject                  = "DeleteObject"
	OpGetObjectTagging              = "GetObjectTagging"
	OpPutObjectTagging              = "PutObjectTagging"
	OpDeleteObjectTagging           = "DeleteObjectTagging"
	OpGetObjectAcl                  = "GetObjectAcl"
	OpGetObjectRetention            = "GetObjectRetention"
	OpPutObjectRetention            = "PutObjectRetention"
	OpGetObjectLegalHold            = "GetObjectLegalHold"
	OpPutObjectLegalHold            = "PutObjectLegalHold"
	OpPutObjectAcl                  = "PutObjectAcl"
	OpCreateMultipartUpload         = "CreateMultipartUpload"
	OpUploadPart                    = "UploadPart"
	OpUploadPartCopy                = "UploadPartCopy"
	OpCompleteMultipartUpload       = "CompleteMultipartUpload"
	OpAbortMultipartUpload          = "AbortMultipartUpload"
	OpListParts                     = "ListParts"
)

// Actions some operation authorizes.
const (
	ActionAbortMultipartUpload             = "s3:AbortMultipartUpload"
	ActionBypassGovernanceRetention        = "s3:BypassGovernanceRetention"
	ActionDeleteObject                     = "s3:DeleteObject"
	ActionDeleteObjectTagging              = "s3:DeleteObjectTagging"
	ActionDeleteObjectVersion              = "s3:DeleteObjectVersion"
	ActionDeleteObjectVersionTagging       = "s3:DeleteObjectVersionTagging"
	ActionGetBucketAcl                     = "s3:GetBucketAcl"
	ActionGetBucketCORS                    = "s3:GetBucketCORS"
	ActionGetBucketLocation                = "s3:GetBucketLocation"
	ActionGetBucketObjectLockConfiguration = "s3:GetBucketObjectLockConfiguration"
	ActionGetBucketOwnershipControls       = "s3:GetBucketOwnershipControls"
	ActionGetBucketPolicy                  = "s3:GetBucketPolicy"
	ActionGetBucketPolicyStatus            = "s3:GetBucketPolicyStatus"
	ActionGetBucketPublicAccessBlock       = "s3:GetBucketPublicAccessBlock"
	ActionGetBucketVersioning              = "s3:GetBucketVersioning"
	ActionGetEncryptionConfiguration       = "s3:GetEncryptionConfiguration"
	ActionGetObject                        = "s3:GetObject"
	ActionGetObjectAcl                     = "s3:GetObjectAcl"
	ActionGetObjectLegalHold               = "s3:GetObjectLegalHold"
	ActionGetObjectRetention               = "s3:GetObjectRetention"
	ActionGetObjectTagging                 = "s3:GetObjectTagging"
	ActionGetObjectVersion                 = "s3:GetObjectVersion"
	ActionGetObjectVersionAcl              = "s3:GetObjectVersionAcl"
	ActionGetObjectVersionTagging          = "s3:GetObjectVersionTagging"
	ActionListAllMyBuckets                 = "s3:ListAllMyBuckets"
	ActionListBucket                       = "s3:ListBucket"
	ActionListBucketMultipartUploads       = "s3:ListBucketMultipartUploads"
	ActionListBucketVersions               = "s3:ListBucketVersions"
	ActionListMultipartUploadParts         = "s3:ListMultipartUploadParts"
	ActionPutObject                        = "s3:PutObject"
	ActionPutObjectLegalHold               = "s3:PutObjectLegalHold"
	ActionPutObjectRetention               = "s3:PutObjectRetention"
	ActionPutObjectTagging                 = "s3:PutObjectTagging"
	ActionPutObjectVersionTagging          = "s3:PutObjectVersionTagging"
)

var operations = []Operation{
	{
		Name:    OpListBuckets,
		Scope:   ScopeService,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListAllMyBuckets, On: OnTarget},
		},
		Note: "answered from the store; lists the requester's own buckets, authorized by the user policy alone",
	},
	{
		Name:    OpHeadBucket,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListBucket, On: OnTarget},
		},
	},
	{
		Name:    OpListObjects,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListBucket, On: OnTarget},
		},
	},
	{
		Name:    OpListObjectsV2,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListBucket, On: OnTarget},
		},
	},
	{
		Name:    OpListObjectVersions,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListBucketVersions, On: OnTarget},
		},
	},
	{
		Name:    OpListMultipartUploads,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListBucketMultipartUploads, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketLocation,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketLocation, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketAcl,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketAcl, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketPolicy,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketPolicy, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketPolicyStatus,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketPolicyStatus, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketCors,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketCORS, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketVersioning,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketVersioning, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketEncryption,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetEncryptionConfiguration, On: OnTarget},
		},
	},
	{
		Name:    OpGetBucketOwnershipControls,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketOwnershipControls, On: OnTarget},
		},
	},
	{
		Name:    OpGetPublicAccessBlock,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketPublicAccessBlock, On: OnTarget},
		},
	},
	{
		Name:    OpGetObjectLockConfiguration,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetBucketObjectLockConfiguration, On: OnTarget},
		},
	},
	{
		Name:    OpDeleteObjects,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionDeleteObject, On: OnEachKey, VersionAction: ActionDeleteObjectVersion},
			{Action: ActionBypassGovernanceRetention, On: OnEachKey, Header: "x-amz-bypass-governance-retention"},
		},
	},
	{
		Name:    OpPostObject,
		Scope:   ScopeBucket,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
			{Action: ActionPutObjectTagging, On: OnTarget, Header: "x-amz-tagging"},
		},
		Note: "browser-based POST upload; header names the form field",
	},
	{
		Name:    OpCreateBucket,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "buckets are created by the control plane",
	},
	{
		Name:    OpDeleteBucket,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "buckets are deleted by the control plane",
	},
	{
		Name:    OpPutBucketAcl,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "ACLs are disabled",
	},
	{
		Name:    OpPutBucketPolicy,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpDeleteBucketPolicy,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutBucketCors,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpDeleteBucketCors,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutBucketVersioning,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutObjectLockConfiguration,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutBucketEncryption,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpDeleteBucketEncryption,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutBucketOwnershipControls,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpDeleteBucketOwnershipControls,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpPutPublicAccessBlock,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpDeletePublicAccessBlock,
		Scope:   ScopeBucket,
		Support: Refused,
		Note:    "bucket configuration is written where the bucket is created, not through the S3 API",
	},
	{
		Name:    OpGetObject,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObject, On: OnTarget, VersionAction: ActionGetObjectVersion},
		},
	},
	{
		Name:    OpHeadObject,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObject, On: OnTarget, VersionAction: ActionGetObjectVersion},
		},
	},
	{
		Name:    OpGetObjectAttributes,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObject, On: OnTarget, VersionAction: ActionGetObjectVersion},
		},
	},
	{
		Name:    OpPutObject,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
			{Action: ActionPutObjectTagging, On: OnTarget, Header: "x-amz-tagging"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-mode"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-retain-until-date"},
			{Action: ActionPutObjectLegalHold, On: OnTarget, Header: "x-amz-object-lock-legal-hold"},
		},
	},
	{
		Name:    OpCopyObject,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
			{Action: ActionPutObjectTagging, On: OnTarget, Header: "x-amz-tagging"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-mode"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-retain-until-date"},
			{Action: ActionPutObjectLegalHold, On: OnTarget, Header: "x-amz-object-lock-legal-hold"},
			{Action: ActionGetObject, On: OnCopySource, VersionAction: ActionGetObjectVersion},
		},
	},
	{
		Name:    OpDeleteObject,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionDeleteObject, On: OnTarget, VersionAction: ActionDeleteObjectVersion},
			{Action: ActionBypassGovernanceRetention, On: OnTarget, Header: "x-amz-bypass-governance-retention"},
		},
	},
	{
		Name:    OpGetObjectTagging,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObjectTagging, On: OnTarget, VersionAction: ActionGetObjectVersionTagging},
		},
	},
	{
		Name:    OpPutObjectTagging,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObjectTagging, On: OnTarget, VersionAction: ActionPutObjectVersionTagging},
		},
	},
	{
		Name:    OpDeleteObjectTagging,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionDeleteObjectTagging, On: OnTarget, VersionAction: ActionDeleteObjectVersionTagging},
		},
	},
	{
		Name:    OpGetObjectAcl,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObjectAcl, On: OnTarget, VersionAction: ActionGetObjectVersionAcl},
		},
	},
	{
		Name:    OpGetObjectRetention,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObjectRetention, On: OnTarget},
		},
	},
	{
		Name:    OpPutObjectRetention,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObjectRetention, On: OnTarget},
			{Action: ActionBypassGovernanceRetention, On: OnTarget, Header: "x-amz-bypass-governance-retention"},
		},
	},
	{
		Name:    OpGetObjectLegalHold,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionGetObjectLegalHold, On: OnTarget},
		},
	},
	{
		Name:    OpPutObjectLegalHold,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObjectLegalHold, On: OnTarget},
		},
	},
	{
		Name:    OpPutObjectAcl,
		Scope:   ScopeObject,
		Support: Refused,
		Note:    "ACLs are disabled",
	},
	{
		Name:    OpCreateMultipartUpload,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
			{Action: ActionPutObjectTagging, On: OnTarget, Header: "x-amz-tagging"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-mode"},
			{Action: ActionPutObjectRetention, On: OnTarget, Header: "x-amz-object-lock-retain-until-date"},
			{Action: ActionPutObjectLegalHold, On: OnTarget, Header: "x-amz-object-lock-legal-hold"},
		},
	},
	{
		Name:    OpUploadPart,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
		},
	},
	{
		Name:    OpUploadPartCopy,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
			{Action: ActionGetObject, On: OnCopySource, VersionAction: ActionGetObjectVersion},
		},
	},
	{
		Name:    OpCompleteMultipartUpload,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionPutObject, On: OnTarget},
		},
	},
	{
		Name:    OpAbortMultipartUpload,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionAbortMultipartUpload, On: OnTarget},
		},
	},
	{
		Name:    OpListParts,
		Scope:   ScopeObject,
		Support: Supported,
		Authorizations: []Authorization{
			{Action: ActionListMultipartUploadParts, On: OnTarget},
		},
	},
}

var actions = []string{
	ActionAbortMultipartUpload,
	ActionBypassGovernanceRetention,
	ActionDeleteObject,
	ActionDeleteObjectTagging,
	ActionDeleteObjectVersion,
	ActionDeleteObjectVersionTagging,
	ActionGetBucketAcl,
	ActionGetBucketCORS,
	ActionGetBucketLocation,
	ActionGetBucketObjectLockConfiguration,
	ActionGetBucketOwnershipControls,
	ActionGetBucketPolicy,
	ActionGetBucketPolicyStatus,
	ActionGetBucketPublicAccessBlock,
	ActionGetBucketVersioning,
	ActionGetEncryptionConfiguration,
	ActionGetObject,
	ActionGetObjectAcl,
	ActionGetObjectLegalHold,
	ActionGetObjectRetention,
	ActionGetObjectTagging,
	ActionGetObjectVersion,
	ActionGetObjectVersionAcl,
	ActionGetObjectVersionTagging,
	ActionListAllMyBuckets,
	ActionListBucket,
	ActionListBucketMultipartUploads,
	ActionListBucketVersions,
	ActionListMultipartUploadParts,
	ActionPutObject,
	ActionPutObjectLegalHold,
	ActionPutObjectRetention,
	ActionPutObjectTagging,
	ActionPutObjectVersionTagging,
}
