// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: write.sql

package writedb

import (
	"context"
)

const createAccessKey = `-- name: CreateAccessKey :exec
INSERT INTO access_keys (access_key_id, user_id, secret_access_key) VALUES (?, ?, ?)
`

type CreateAccessKeyParams struct {
	AccessKeyID     string
	UserID          int64
	SecretAccessKey string
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAccessKey, arg.AccessKeyID, arg.UserID, arg.SecretAccessKey)
	return err
}

const createBucket = `-- name: CreateBucket :exec
INSERT INTO buckets (tenant_id, name, backend, policy, cors) VALUES (?, ?, ?, ?, ?)
`

type CreateBucketParams struct {
	TenantID int64
	Name     string
	Backend  string
	Policy   string
	Cors     string
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) error {
	_, err := q.db.ExecContext(ctx, createBucket,
		arg.TenantID,
		arg.Name,
		arg.Backend,
		arg.Policy,
		arg.Cors,
	)
	return err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name) VALUES (?) RETURNING id
`

// Write queries used by the admin tooling / control plane only.
// The proxy must never import the package generated from this file.
func (q *Queries) CreateTenant(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, name) VALUES (?, ?) RETURNING id
`

type CreateUserParams struct {
	TenantID int64
	Name     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.TenantID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
