package sigv4_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/fujiwara/s3rp/sigv4"
)

// Cross-implementation check: requests signed by botocore — the SigV4
// implementation every boto3/aws-cli client carries — must verify. The
// verifier re-signs a clone with aws-sdk-go-v2's signer, so Go-SDK-signed
// requests (the fuzz targets) share the signing code with the verifier and
// cannot catch an asymmetry in how the clone is built; an independent
// signer can. Vectors are generated by testdata/crosscheck/generate.py and
// record the wire request exactly; S3RP_CROSSCHECK_DIR names a directory
// of additional vector files, which is how CI feeds freshly generated ones.

type crossCheckVector struct {
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Method          string      `json:"method"`
	Host            string      `json:"host"`
	URI             string      `json:"uri"`
	Headers         [][2]string `json:"headers"`
	AccessKeyID     string      `json:"access_key_id"`
	SecretAccessKey string      `json:"secret_access_key"`
	SessionToken    string      `json:"session_token"`
	Region          string      `json:"region"`
	Timestamp       string      `json:"timestamp"`
	PayloadHash     string      `json:"payload_hash"`
}

type crossCheckFile struct {
	Generator       string             `json:"generator"`
	BotocoreVersion string             `json:"botocore_version"`
	Vectors         []crossCheckVector `json:"vectors"`
}

func crossCheckFiles(t *testing.T) []string {
	t.Helper()
	files, err := filepath.Glob(filepath.Join("testdata", "crosscheck", "*.json"))
	if err != nil {
		t.Fatal(err)
	}
	if dir := os.Getenv("S3RP_CROSSCHECK_DIR"); dir != "" {
		extra, err := filepath.Glob(filepath.Join(dir, "*.json"))
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, extra...)
	}
	if len(files) == 0 {
		t.Fatal("no cross-check vector files found")
	}
	return files
}

func TestCrossCheckBotocore(t *testing.T) {
	for _, file := range crossCheckFiles(t) {
		data, err := os.ReadFile(file)
		if err != nil {
			t.Fatal(err)
		}
		var doc crossCheckFile
		if err := json.Unmarshal(data, &doc); err != nil {
			t.Fatalf("%s: %v", file, err)
		}
		if len(doc.Vectors) == 0 {
			t.Fatalf("%s: no vectors", file)
		}
		t.Run(filepath.Base(file), func(t *testing.T) {
			for _, v := range doc.Vectors {
				t.Run(v.Name, func(t *testing.T) { runCrossCheckVector(t, v) })
			}
		})
	}
}

func runCrossCheckVector(t *testing.T, v crossCheckVector) {
	signingTime, err := time.Parse(time.RFC3339, v.Timestamp)
	if err != nil {
		t.Fatalf("timestamp: %v", err)
	}
	// the URI field is the wire form: build the request the way the server
	// does, with RequestURI carrying it verbatim and URL parsed from it —
	// not through a client-side URL round-trip that could re-escape it
	u, err := url.ParseRequestURI(v.URI)
	if err != nil {
		t.Fatalf("uri %q: %v", v.URI, err)
	}
	sr := &http.Request{
		Method:     v.Method,
		URL:        u,
		RequestURI: v.URI,
		Host:       v.Host,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		Header:     http.Header{},
		Body:       http.NoBody,
		RemoteAddr: "192.0.2.1:1234",
	}
	for _, h := range v.Headers {
		sr.Header.Add(h[0], h[1])
	}

	verifier := sigv4.NewVerifier()
	verifier.Now = func() time.Time { return signingTime }
	lookup := func(_ context.Context, accessKeyID, _ string) (sigv4.Credential, error) {
		if accessKeyID != v.AccessKeyID {
			return sigv4.Credential{}, sigv4.ErrUnknownKey
		}
		return sigv4.Credential{SecretAccessKey: v.SecretAccessKey, SessionToken: v.SessionToken}, nil
	}

	got, s3e := verifier.Verify(sr, lookup)
	if s3e != nil {
		t.Fatalf("botocore-signed request refused: %v\n%s %s\nheaders: %v", s3e, v.Method, v.URI, v.Headers)
	}
	if got.AccessKeyID != v.AccessKeyID {
		t.Errorf("access key %q, want %q", got.AccessKeyID, v.AccessKeyID)
	}
	if got.Region != v.Region {
		t.Errorf("region %q, want %q", got.Region, v.Region)
	}
	if got.PayloadHash != v.PayloadHash {
		t.Errorf("payload hash %q, want %q", got.PayloadHash, v.PayloadHash)
	}
	if !got.SigningTime.Equal(signingTime) {
		t.Errorf("signing time %v, want %v", got.SigningTime, signingTime)
	}
}
