// Code generated by s3gw/internal/checksumgen; DO NOT EDIT.

package s3xml

// Checksums is the per-algorithm checksum elements of a body, embedded so
// they sit directly in the enclosing element as S3 lays them out.
type Checksums struct {
	ChecksumCRC32     string `xml:"ChecksumCRC32,omitempty"`
	ChecksumCRC32C    string `xml:"ChecksumCRC32C,omitempty"`
	ChecksumCRC64NVME string `xml:"ChecksumCRC64NVME,omitempty"`
	ChecksumSHA1      string `xml:"ChecksumSHA1,omitempty"`
	ChecksumSHA256    string `xml:"ChecksumSHA256,omitempty"`
	ChecksumSHA512    string `xml:"ChecksumSHA512,omitempty"`
	ChecksumMD5       string `xml:"ChecksumMD5,omitempty"`
	ChecksumXXHASH64  string `xml:"ChecksumXXHASH64,omitempty"`
	ChecksumXXHASH3   string `xml:"ChecksumXXHASH3,omitempty"`
	ChecksumXXHASH128 string `xml:"ChecksumXXHASH128,omitempty"`
}
