name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - '1.25'
          - '1.26'
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build & Test
        run: |
          go test -race ./...

  integration:
    name: Integration (${{ matrix.backend }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: versitygw
            endpoint: "http://localhost:7070"
          - backend: ceph
            endpoint: "http://127.0.0.1:7480"
    steps:
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'

      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Start backend
        run: |
          docker compose up -d --wait "$BACKEND"
        env:
          BACKEND: ${{ matrix.backend }}

      - name: Integration Test
        run: |
          go test -race -run TestIntegration -v ./...
        env:
          S3RP_TEST_BACKEND_ENDPOINT: ${{ matrix.endpoint }}
